services:
  identidock:
    build: .
    expose:
    - "9090"
    environment:
      ENV: PROD
    links:
    - dnmonster
    - redis
    - jenkins

  dnmonster:
    image: amouat/dnmonster

  redis:
    image: redis

